kind: ReplicationController
apiVersion: v1
metadata:
  name: livy
spec:
  replicas: 1
  selector:
    component: livy
  template:
    metadata:
      labels:
        component: livy
    spec:
      containers:
        - name: livy
          # image: livy-img:latest
          image: gcr.io/summer-surfer-203320/livy-img:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8998
          # resources:
            # requests:
            #   memory: "64Mi"
            #   cpu: "250m"
            # limits:
            #   memory: "250Mi"
            #   cpu: "100m"

---
kind: Service
apiVersion: v1
metadata:
  name: livy
spec:
  ports:
    - port: 8998
      targetPort: 8998
      name: http
  selector:
    component: livy
