kind: ReplicationController
apiVersion: v1
metadata:
  name: rstudio
spec:
  replicas: 1
  selector:
    component: rstudio
  template:
    metadata:
      labels:
        component: rstudio
    spec:
      containers:
        - name: rstudio
          # image: rstudio-img:latest
          image: gcr.io/summer-surfer-203320/rstudio-img:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8787
          # resources:
          #   requests:
          #     cpu: 100m
