kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: spark-img:latest
          # image: gcr.io/summer-surfer-203320/spark-img:latest
          imagePullPolicy: IfNotPresent
          command:
          - "/bin/bash"
          - "-c"
          - "--"
          args :
          - './start-master.sh ; sleep infinity'
          ports:
            - containerPort: 7077
            - containerPort: 8080
          # resources:
            # requests:
            #   memory: "250Mi"
            #   cpu: "250m"
            # limits:
            #   memory: "250Mi"
            #   cpu: "100m"
---
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  type: LoadBalancer
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    component: spark-master
