kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-ui
spec:
  replicas: 1
  selector:
    component: spark-ui
  template:
    metadata:
      labels:
        component: spark-ui
    spec:
      containers:
        - name: spark-ui
          image: spark-ui-img:latest
          # image: gcr.io/summer-surfer-203320/spark-ui-img:latest
          ports:
            - containerPort: 80
          # resources:
            # requests:
            #   memory: "250Mi"
            #   cpu: "250m"
            # limits:
            #   memory: "250Mi"
            #   cpu: "100m"
          args:
            - spark-master:8080
          livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 120
              timeoutSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: spark-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    component: spark-ui
